version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 4
      semver-patch-days: 7
    open-pull-requests-limit: 7
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 4
      semver-patch-days: 7
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
