name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pnpm/setup@v2.1.0
        with:
          runtime: node@26
          cache: true
          install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (Chrome)
        run: pnpm run build

      - name: Build (Firefox)
        run: pnpm run build-firefox
