name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (Chrome)
        run: pnpm run build

      - name: Build (Firefox)
        run: pnpm run build-firefox
