name: E2E Test

on:
  schedule:
    # every day 3:00 JST
    - cron: "0 3 * * *"
      timezone: "Asia/Tokyo"

  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - uses: pnpm/setup@v2.0.2
        with:
          runtime: node@26
          cache: true
          install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps chromium

      - name: Run E2E tests
        run: pnpm test
